name: File Changes Analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Analyze changes
        id: analyze
        run: |
          changed_files=$(curl -s -X GET -G \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data-urlencode "base=${{ github.base_ref }}" \
            --data-urlencode "head=${{ github.head_ref }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            | jq -r '.[] | .filename + " " + .status')

          while IFS= read -r line; do
            file=$(echo "$line" | cut -d ' ' -f 1)
            status=$(echo "$line" | cut -d ' ' -f 2)
            
            if [[ $status == "added" ]]; then
              echo "File added: $file"
              echo "File content:"
              cat "$file"
              echo
            elif [[ $status == "modified" ]]; then
              echo "File modified: $file"
              echo "Old file content:"
              git show "${{ github.base_ref }}:$file"
              echo
              echo "New file content:"
              cat "$file"
              echo
              echo "Diff:"
              git diff "${{ github.base_ref }}:$file" "$file"
              echo
            elif [[ $status == "deleted" ]]; then
              echo "File deleted: $file"
              echo "Content: Nothing"
              echo
            fi
          done <<< "$changed_files"
