name: File Changes Analysis
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze_changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analyze changes
        id: analyze
        run: |
          changed_files=$(curl -s -X GET -G \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data-urlencode "base=${{ github.base_ref }}" \
            --data-urlencode "head=${{ github.head_ref }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" \
            | jq -r '.[] | .filename + " " + .status')

          while IFS= read -r line; do
            file=$(echo "$line" | cut -d ' ' -f 1)
            status=$(echo "$line" | cut -d ' ' -f 2)
            
            if [[ $status == "added" ]]; then
              echo "File added: $file"
              echo "File content:"
              cat "$file"
              echo
              ls -l chatgpt_agent.py
              python chatgpt_agent.py  --file "$file" --content "$(cat "$file")"
            elif [[ $status == "modified" ]]; then
              echo "File modified: $file"
              echo "Old file content:"
              git show "HEAD:${file}"
              echo
              echo "New file content:"
              cat "$file"
              echo
              echo "Diff:"
              git diff "HEAD:${file}" "$file"
              echo
              python chatgpt_agent.py --file "$file" --old-content "$(git show "HEAD:${file}")" --new-content "$(cat "$file")"
            elif [[ $status == "deleted" ]]; then
              echo "File deleted: $file"
              echo "Content: Nothing"
              echo
            fi
          done <<< "$changed_files"
