name: PR Diff Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  diff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Checkout Head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head

      - name: Get PR Diff
        id: diff
        run: |
          FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }})
          echo "::set-output name=files::$FILES"

      - name: Detect Programming Language
        uses: aslafy-z/github-action-detect-language@master
        id: detect-lang
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Process Files and Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            const files = '${{ steps.diff.outputs.files }}'.split('\n');
            const language = '${{ steps.detect-lang.outputs.language }}';
            for (const file of files) {
              const baseContent = fs.existsSync(`base/${file}`) ? fs.readFileSync(`base/${file}`, 'utf8') : '';
              const headContent = fs.existsSync(`head/${file}`) ? fs.readFileSync(`head/${file}`, 'utf8') : '';
              const diff = execSync(`diff -u base/${file} head/${file}`, { encoding: 'utf8' });
              const result = execSync(`python3 chatgpt_agent.py '${baseContent}' '${diff}' '${language}'`, { encoding: 'utf8' });
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Results for ${file}:\n\n${result}`
              });
            }
