name: PR Code Review Bot Pipeline

permissions:
  issues: write

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  diff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Base
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Checkout Head
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: head

      - name: Get PR Diff
        id: diff
        run: |
          cd base
          git fetch origin ${{ github.head_ref }}
          FILES=$(git diff --name-only ${{ github.base_ref }} FETCH_HEAD)
          echo "::set-output name=files::$FILES"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: head/requirements.txt
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"

      - uses: mshick/add-pr-comment@v2
        with:
          message: "This is a comment on the pull request."
