name: Process Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Process Files
        id: process_files
        run: |
          #!/bin/bash

          # Get the pull request information
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          PR_BASE_BRANCH=$(jq --raw-output .pull_request.base.ref "$GITHUB_EVENT_PATH")

          # Fetch the base branch
          git fetch origin $PR_BASE_BRANCH:$PR_BASE_BRANCH

          # Create a temporary directory
          TEMP_DIR=$(mktemp -d)
          echo "Using temporary directory: $TEMP_DIR"

          # Get the files changed in the pull request
          CHANGED_FILES=$(git diff --name-status $PR_BASE_BRANCH)
          echo "Changed files: $CHANGED_FILES"

          # Prepare arrays to store file names
          ADDED_FILES=()
          MODIFIED_FILES=()
          DIFF_FILES=()

          # Process each changed file
          while IFS=$'\t' read -r STATUS FILE; do
            echo "Processing file: $FILE"
            if [[ -f $FILE ]]; then
              # Make sure the directory exists
              DIRNAME=$(dirname "$FILE")
              mkdir -p "$TEMP_DIR/$DIRNAME"
              if [[ $STATUS == "A" ]]; then
                # File was added
                FILE_NAME="$TEMP_DIR/${FILE}"
                echo "$FILE" > "$FILE_NAME"
                ADDED_FILES+=("$FILE")
                echo "Added file: $FILE"
              elif [[ $STATUS == "M" ]]; then
                # File was modified
                FILE_NAME="$TEMP_DIR/${FILE}"
                echo "$FILE" > "$FILE_NAME"
                MODIFIED_FILES+=("$FILE")
                echo "Modified file: $FILE"

                DIFF_FILE_NAME="${FILE}.diff"
                DIFF_FILE="$TEMP_DIR/$DIFF_FILE_NAME"
                DIFF=$(git diff $PR_BASE_BRANCH "$FILE")
                echo "$DIFF" > "$DIFF_FILE"
                DIFF_FILES+=("$DIFF_FILE_NAME")
                echo "Diff file: $DIFF_FILE_NAME"
              fi
            fi
            done <<< "$CHANGED_FILES"
            echo "Added files: ${ADDED_FILES[*]}"
            echo "Modified files: ${MODIFIED_FILES[*]}"
            echo "Diff files: ${DIFF_FILES[*]}"
            echo "Temp dir content: $(ls -lR $TEMP_DIR)"

            # Set the step outputs
            echo "temp_dir=$TEMP_DIR" >> "$GITHUB_OUTPUT"
            echo "added_files=${ADDED_FILES[*]}" >> "$GITHUB_OUTPUT"
            echo "modified_files=${MODIFIED_FILES[*]}" >> "$GITHUB_OUTPUT"
            echo "diff_files=${DIFF_FILES[*]}" >> "$GITHUB_OUTPUT"

      - name: Run Python Script
        run: |
          python analyze.py --temp-dir "${{ steps.process_files.outputs.temp_dir }}" --added "${{ steps.process_files.outputs.added_files }}" --modified "${{ steps.process_files.outputs.modified_files }}" --diffs "${{ steps.process_files.outputs.diff_files }}"
